---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nats
  labels:
    app: nats
    service: nats
data:
  nats-server.conf: |
    host: 0.0.0.0
    port: 4222
    monitor_port: 8222
    debug: false
    jetstream: true
    websocket {
      port: 8080
      no_tls: true
      same_origin: false
    }