---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
    service: nats
spec:
  ports:
    - name: nats
      port: 4222
      targetPort: nats
      protocol: TCP
    - name: ws
      port: 8080
      targetPort: ws
      protocol: TCP
  selector:
    app: nats
