---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  labels:
    app: nats
    service: nats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
