---
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1server-snippets
  value: |
    map $http_upgrade $type {
      default "web";
      websocket "ws";
    }
    location @ws {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $httphost;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $remoteaddr;
      proxy_cache_bypass $http_upgrade;
    }
