---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: docker-secret
      initContainers:
        - name: init
          image: default-api
          imagePullPolicy: Always
          args:
            - init
          envFrom:
            - configMapRef:
                name: configmap-api
      containers:
        - name: api
          image: default-api
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-api
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: to-be-replaced
              memory: to-be-replaced
            requests:
              cpu: to-be-replaced
              memory: to-be-replaced
          startupProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
