---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-websockets
  labels:
    app: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-websockets
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-websockets
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: api-websockets
          image: default-api
          imagePullPolicy: Always
          command: ['node', './dist/src/entrypoints/wss.js']
          envFrom:
            - configMapRef:
                name: configmap-api
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 512Mi
              cpu: 400m
