---
apiVersion: v1
kind: Service
metadata:
  name: api-websockets-service
  labels:
    app: api
    stack: node
    tier: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: api-websockets
  type: ClusterIP
