---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-worker
  labels:
    app: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-worker
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: api-worker
          image: default-api
          imagePullPolicy: Always
          command: ['node', './dist/src/entrypoints/worker.js']
          args: ['--queue="system"']
          envFrom:
            - configMapRef:
                name: configmap-api
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 400m
