---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-worker
  labels:
    app: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-worker
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: api-worker
          image: default-api
          command: ["node", "./dist/src/entrypoints/worker.js"]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-api
          resources:
            requests:
              memory: "100Mi"
              cpu: 25m
            limits:
              memory: "400Mi"
              cpu: 200m
