---
configMapGenerator:
  - name: configmap-web
    envs:
      - config/env.properties
resources:
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app: web
      stack: vue
      tier: frontend
    includeTemplates: true
