---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-redis
data:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-file
data:
  redis.conf: |
    maxmemory 225mb
    maxmemory-policy allkeys-lru
    maxclients 12000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
    aclfile /usr/local/etc/redis/users.acl
  users.acl: |
    user default on nopass sanitize-payload ~* &* +@all
