---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-redis
  labels:
    app: redis
    service: redis
data:
  redis.conf: |
    maxmemory 250mb
    maxmemory-policy allkeys-lru
    maxclients 12000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
    aclfile /usr/local/etc/redis/users.acl
  users.acl: |
    ### EXAMPLE
    # user default off
    # user development +subscribe +psubscribe +publish -@all on >PASSWORD
    ### Create passwords in a random redis docker with:
    ### >redis-cli
    ### >ACL GENPASS 600

