---
configMapGenerator:
  - name: configmap-redis
    envs:
      - config/env.properties
  - name: redis-config-file
    files:
      - config/redis.conf
      - config/users.acl
secretGenerator:
  - name: secrets-redis
    envs:
      - config/secrets.properties
resources:
  - service.yaml
  - statefulset.yaml
  - volume.yaml
images:
  - name: default-redis
    newName: redis
    newTag: 7-alpine
labels:
  - pairs:
      app: redis
      service: redis
      tier: service
    includeTemplates: true
