---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    service: redis
spec:
  clusterIP: None
  ports:
    - name: http
      port: 6379
      targetPort: http
  selector:
    app: redis
