---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  serviceName: redis
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: redis
      service: redis
  template:
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: redis
          image: default-redis
          imagePullPolicy: Always
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: configmap-redis
            - secretRef:
                name: secrets-redis
          volumeMounts:
            - name: redis-pv
              mountPath: /data  # Must match configmap
            - name: redis-config
              mountPath: /usr/local/etc/redis
          startupProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: redis
          readinessProbe:
            tcpSocket:
              port: redis
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config-file
