---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-scheduler
  labels:
    app: api
    stack: node
    tier: backend
spec:
  schedule: '*/30 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: docker-secret
          containers:
            - name: api-scheduler
              image: default-api
              imagePullPolicy: Always
              command: ['node', './dist/src/entrypoints/cronjob.js']
              envFrom:
                - configMapRef:
                    name: configmap-api
                - secretRef:
                    name: secrets-api
              resources:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 512Mi
                  cpu: 400m
          restartPolicy: OnFailure
