---
configMapGenerator:
  - name: configmap-typesense
    envs:
      - config/env.properties
secretGenerator:
  - name: secrets-typesense
    envs:
      - config/secrets.properties
resources:
  - service.yaml
  - statefulset.yaml
  - volume.yaml
images:
  - name: default-typesense
    newName: typesense/typesense
    newTag: '26.0'
labels:
  - pairs:
      app: typesense
      service: typesense
      tier: service
    includeTemplates: true
