---
apiVersion: v1
kind: Service
metadata:
  name: typesense
  labels:
    app: typesense
    service: typesense
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8108
      targetPort: http
  selector:
    app: typesense
