---
apiVersion: v1
kind: Service
metadata:
  name: typesense
  labels:
    app: typesense
    service: typesense
spec:
  clusterIP: None
  ports:
    - name: typesense
      port: 8108
      targetPort: typesense
  selector:
    app: typesense
