---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  labels:
    app: typesense
    service: typesense
spec:
  serviceName: typesense
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      service: typesense
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
        service: typesense
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 300
      containers:
        - name: typesense
          image: typesense/typesense:26.0
          command:
            - '/opt/typesense-server'
            - '-d'
            - '/usr/share/typesense/data'
            - '-a'
            - 'ldflDFA212sDFSKLJLJ234567jhfhgdg'
            - '--api-port'
            - '8108'
            - '--peering-port'
            - '8107'
          ports:
            - containerPort: 8108
              name: http
          resources:
            requests:
              memory: 250Mi
              cpu: 64m
            limits:
              memory: 1024Mi
              cpu: 512m
          volumeMounts:
            - name: typesense-pv
              mountPath: /usr/share/typesense/data
      volumes:
        - name: typesense-pv
          persistentVolumeClaim:
            claimName: typesense-pvc
