---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  labels:
    app: typesense
spec:
  serviceName: typesense
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: typesense
      service: typesense
  template:
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 300
      containers:
        - name: typesense
          image: default-typesense
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-typesense
          ports:
            - containerPort: 8108  # Must match configmap
              name: typesense
          resources:
            requests:
              memory: 256Mi
              cpu: 50m
            limits:
              memory: 1024Mi
              cpu: 500m
          volumeMounts:
            - name: typesense-pv
              mountPath: /usr/share/typesense/data  # Must match configmap
          startupProbe:
            tcpSocket:
              port: typesense
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: typesense
          readinessProbe:
            tcpSocket:
              port: typesense
      volumes:
        - name: typesense-pv
          persistentVolumeClaim:
            claimName: typesense-pvc
