---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-pvc
  labels:
    app: typesense
    service: typesense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
