---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/kubernetes/ingress-nginx//deploy/static/provider/cloud/?ref=controller-v1.12.1
patches:
  - path: patches/ingress-nginx-controller-configmap.yaml
    target:
      kind: ConfigMap
      name: ingress-nginx-controller
      namespace: ingress-nginx
  - path: patches/ingress-nginx-controller-service.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
  - path: patches/ingress-nginx-jobs.yaml
    target:
      kind: Job
      namespace: ingress-nginx
