---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      initContainers:
        - name: init
          image: default-matomo
          imagePullPolicy: Always
          args:
            - init
          envFrom:
            - configMapRef:
                name: configmap-matomo
          volumeMounts:
            - mountPath: /var/www/html
              name: html-files
      containers:
        - name: matomo
          image: default-matomo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: to-be-replaced
              memory: to-be-replaced
            requests:
              cpu: to-be-replaced
              memory: to-be-replaced
          volumeMounts:
            - mountPath: /var/www/html
              name: html-files
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: html-files
          persistentVolumeClaim:
            claimName: matomo-data-pvc
