---
namespace: matomo
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - volume.yaml
images:
  - name: default-matomo
    newName: ghcr.io/wisemen-digital/matomo
    newTag: latest
labels:
  - pairs:
      app: matomo
      service: matomo
      tier: service
    includeTemplates: true
