---
namespace: matomo
resources:
  - ../../common/base/
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - volume.yaml
images:
  - name: default-matomo
    newName: ghcr.io/wisemen-digital/matomo
    newTag: latest
labels:
  - pairs:
      app: matomo
      service: matomo
      tier: service
    includeTemplates: true
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
