---
apiVersion: v1
kind: Service
metadata:
  name: matomo-service
  namespace: matomo
  labels:
    app: matomo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: matomo
