---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data-pvc
  namespace: matomo
  labels:
    app: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
