---
namespace: signoz-otel-collector
labels:
  - pairs:
      app: signoz-otel-collector
      service: signoz-otel-collector
      tier: service
    includeTemplates: true
resources:
  - configmap.yaml
  - namespace.yaml
  - otel-agent/
  - otel-deployment/
images:
  - name: default-otel-collector
    newName: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    newTag: latest
