---
namespace: signoz-otel-collector
configMapGenerator:
  - name: configmap-otel
    envs:
      - config/env.properties
secretGenerator:
  - name: secrets-otel
    envs:
      - config/secrets.properties
resources:
  - namespace.yaml
  - otel-agent/
  - otel-deployment/
images:
  - name: default-otel-collector
    newName: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    newTag: latest
