---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-scheduler
  labels:
    app: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-scheduler
    spec:
      imagePullSecrets:
        - name: docker-secret
      initContainers:
        - name: init
          image: default-api
          imagePullPolicy: Always
          args:
            - init
          envFrom:
            - configMapRef:
                name: configmap-api
      containers:
        - name: api-scheduler
          image: default-api
          imagePullPolicy: Always
          args:
            - scheduler
          envFrom:
            - configMapRef:
                name: configmap-api
          resources:
            requests:
              memory: 64Mi
              cpu: 25m
            limits:
              memory: 256Mi
              cpu: 100m
