---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-otel-metrics-reporter
  labels:
    app: api
    stack: node
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-otel-metrics-reporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-otel-metrics-reporter
        stack: node
        tier: backend
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: api-otel-metrics-reporter
          image: default-api
          imagePullPolicy: Always
          command: ['node', './dist/src/entrypoints/otel-metrics-reporter.js']
          envFrom:
            - configMapRef:
                name: configmap-api
            - secretRef:
                name: secrets-api
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 50m
