---
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
data:
  # Allow annotations such as `configuration-snippet` & `server-snippet`
  allow-snippet-annotations: 'true'
  annotations-risk-level: 'Critical'
  # Needed according to Scaleway docs, see
  # https://www.scaleway.com/en/docs/tutorials/proxy-protocol-v2-load-balancer/#configuring-proxy-protocol-for-ingress-nginx
  compute-full-forwarded-for: 'true'
  use-forwarded-headers: 'true'
  use-proxy-protocol: 'true'
  # Enable OpenTelemetry
  enable-opentelemetry: 'true'
  otlp-collector-host: 'shared-otel-agent-service.shared-otel-collector.svc.cluster.local'
  opentelemetry-operation-name: 'HTTP $request_method $service_name $uri'
