---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-zitadel
data:
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: root
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: Ziwy0hv5xv2v27e3haic7tbkabaugu8otoobgp.
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: true
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME: Sysops
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME: Wisemen
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS: sysops@wisemen.digital

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-file
data:
  # All possible options and their defaults:
  # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
  zitadel-config.yaml: |
    Log:
      Level: info
    LogStore:
      Access:
        Stdout:
          Enabled: false
    ExternalPort: 443
    ExternalSecure: true
    Database:
      postgres:
        User:
          SSL:
            Mode: 'disable'
        Admin:
          SSL:
            Mode: 'disable'
    Machine:
      Identification:
        Hostname:
          Enabled: true  # Needed otherwise setup gets stuck during migrations
    DefaultInstance:
      OIDCSettings:
        AccessTokenLifetime: 12h
        IdTokenLifetime: 12h
        RefreshTokenIdleExpiration: 720h  # 30 days
        RefreshTokenExpiration: 8640h  # 360 days
