---
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: default
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zitadel-service
                port:
                  name: http
