---
kind: Ingress
metadata:
  name: ingress
  annotations:
    # Needed for gRPC support, see
    # https://zitadel.com/docs/self-hosting/deploy/troubleshooting#ingress-nginx
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleRemoveById 949110
    nginx.ingress.kubernetes.io/backend-protocol: 'GRPC'
    nginx.ingress.kubernetes.io/configuration-snippet: |
        grpc_set_header Host $host;
        more_clear_input_headers "Host" "X-Forwarded-Host";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
    nginx.ingress.kubernetes.io/server-snippet: 'grpc_buffer_size 8k;'
spec:
  rules:
    - host: default
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zitadel-service
                port:
                  name: http
