---
namespace: zitadel
configMapGenerator:
  - name: configmap-zitadel
    envs:
      - config/env.properties
  - name: zitadel-config-file
    files:
      - config/zitadel-config.yaml
resources:
  - ../../common/base/
  - deployment.yaml
  - service.yaml
components:
  - ../../common/components/customize-via-env/
images:
  - name: default-zitadel
    newName: ghcr.io/zitadel/zitadel
    newTag: latest
labels:
  - pairs:
      app: zitadel
      service: zitadel
      tier: service
    includeTemplates: true
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
