---
namespace: zitadel
resources:
  - ../../common/base/
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: default-zitadel
    newName: ghcr.io/zitadel/zitadel
    newTag: latest
labels:
  - pairs:
      app: zitadel
      service: zitadel
      tier: service
    includeTemplates: true
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
