---
apiVersion: v1
kind: Service
metadata:
  name: zitadel-service
  namespace: zitadel
  labels:
    app: zitadel
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: zitadel
