---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: cms
          image: default-cms
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-cms
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1536Mi
              cpu: 1
          livenessProbe:
            httpGet:
              path: /server/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /server/ping
              port: 3000
