---
configMapGenerator:
  - name: configmap-api
    envs:
      - config/env.properties
secretGenerator:
  - name: secrets-api
    envs:
      - config/secrets.properties
resources:
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app: api
      stack: node
      tier: backend
    includeTemplates: true
