---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: api
