---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos
  labels:
    app: benthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benthos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: benthos
          image: docker.redpanda.com/redpandadata/redpanda
          imagePullPolicy: Always
          args: ['connect', 'run']
          envFrom:
            - configMapRef:
                name: configmap-benthos
          volumeMounts:
            - name: config-volume
              mountPath: /connect.yaml
              subPath: connect.yaml
            - name: certs-volume
              mountPath: /certs
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 200m
      volumes:
        - name: config-volume
          configMap:
            name: benthos-config
        - name: certs-volume
          configMap:
            name: certs-config
