---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos
  labels:
    app: benthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benthos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: benthos
          image: default-benthos
          imagePullPolicy: Always
          args: ['run']
          envFrom:
            - configMapRef:
                name: configmap-benthos
          volumeMounts:
            - name: config-volume
              mountPath: /connect.yaml
              subPath: connect.yaml
            - name: certs-volume
              mountPath: /certs
          resources:
            limits:
              cpu: to-be-replaced
              memory: to-be-replaced
            requests:
              cpu: to-be-replaced
              memory: to-be-replaced
      volumes:
        - name: config-volume
          configMap:
            name: benthos-config
        - name: certs-volume
          configMap:
            name: certs-config
