---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: web
          image: default-web
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-web
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 512Mi
              cpu: 200m
          startupProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
