---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: pgbouncer
          image: default-pgbouncer
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-pgbouncer
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            limits:
              cpu: to-be-replaced
              memory: to-be-replaced
            requests:
              cpu: to-be-replaced
              memory: to-be-replaced
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - killall --wait -INT pgbouncer
          startupProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
