---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: pgbouncer
          image: default-pgbouncer
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-pgbouncer
            - secretRef:
                name: secrets-pgbouncer
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64M
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - killall --wait -INT pgbouncer
          startupProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
