---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
    service: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: default-pgbouncer
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-pgbouncer
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64M
          startupProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            tcpSocket:
              port: postgres
          readinessProbe:
            tcpSocket:
              port: postgres
