---
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: default-pgbouncer
    newName: edoburu/pgbouncer
    newTag: latest
labels:
  - pairs:
      app: pgbouncer
      service: pgbouncer
      tier: service
    includeTemplates: true
