---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-deployment-config-file
  labels:
    app: otel-deployment
data:
  otel-deployment-config.yaml: |-
    exporters:
      otlphttp:
        endpoint: https://signoz.internal.appwi.se/otlp
        auth:
          authenticator: basicauth/client
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: localhost:1777
      zpages:
        endpoint: localhost:55679
      basicauth/client:
        client_auth:
          username: test
          password: test123
    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s
      resourcedetection:
        detectors:
          - env
        override: false
        timeout: 2s
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: scaleway
              scheme: https
              http_headers:
                X-Token: 
                  values: 
                    - igc0jtlykqE12NEVNG8YYbT2KHBQQOnd-UmKb1QIMT8vTWdtqhUc5D2zPqj7b2-8
              static_configs:
                - targets:
                  - 4b7d8068-68be-433e-b9e9-4d090ccaac68.metrics.cockpit.nl-ams.scw.cloud
              metrics_path: "prometheus/api/v1/labels"
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
        collection_interval: 30s
        metrics:
          k8s.node.condition:
            enabled: true
          k8s.pod.status_reason:
            enabled: true
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
          - NetworkUnavailable
      k8s_events: null
    service:
      extensions:
        - health_check
        - zpages
        - pprof
        - basicauth/client
      pipelines:
        logs:
          exporters:
            - otlphttp
          processors:
            - resourcedetection
            - batch
          receivers:
            - k8s_events
        metrics:
          exporters:
            - otlphttp
          processors:
            - resourcedetection
            - batch
          receivers:
            - prometheus
        metrics/internal:
          exporters:
            - otlphttp
          processors:
            - resourcedetection
            - batch
          receivers:
            - k8s_cluster
      telemetry:
        logs:
          level: debug
          encoding: console
        metrics:
          address: 0.0.0.0:8888
