---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-deployment-config-file
  labels:
    app: otel-deployment
data:
  otel-deployment-config.yaml: |-
    exporters:
      otlphttp:
        endpoint: https://signoz.internal.appwi.se/otlp
        auth:
          authenticator: basicauth/client
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: localhost:1777
      zpages:
        endpoint: localhost:55679
      basicauth/client:
        client_auth:
          username: test
          password: test123
    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s
      resourcedetection:
        detectors:
          - env
        override: false
        timeout: 2s
    receivers:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
        collection_interval: 30s
        metrics:
          k8s.node.condition:
            enabled: true
          k8s.pod.status_reason:
            enabled: true
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
          - NetworkUnavailable
      k8s_events: null
    service:
      extensions:
        - health_check
        - zpages
        - pprof
        - basicauth/client
      pipelines:
        logs:
          exporters:
            - otlphttp
          processors:
            - resourcedetection
            - batch
          receivers:
            - k8s_events
        metrics/internal:
          exporters:
            - otlphttp
          processors:
            - resourcedetection
            - batch
          receivers:
            - k8s_cluster
      telemetry:
        logs:
          encoding: json
        metrics:
          address: 0.0.0.0:8888
