---
apiVersion: v1
kind: Service
metadata:
  name: otel-deployment-service
  labels:
    app: otel-deployment
spec:
  type: ClusterIP
  ports:
    - name: health-check
      port: 13133
      targetPort: health-check
      protocol: TCP
  selector:
    app: otel-deployment
