---
apiVersion: v1
kind: Service
metadata:
  name: cms-service
  labels:
    app: cms
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: cms
