---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  labels:
    app: otel-agent
spec:
  selector:
    matchLabels:
      app: otel-agent
  minReadySeconds: 5
  template:
    metadata:
      annotations:
      labels:
        app: otel-agent
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: otel-agent
          image: default-otel-collector
          imagePullPolicy: IfNotPresent
          command:
            - '/otelcol-contrib'
          args:
            - '--config=/conf/otel-agent-config.yaml'
          envFrom:
            - configMapRef:
                name: configmap-otel
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: 'service.name=k8s-monitoring,k8s.cluster.name=$(K8S_CLUSTER_NAME),k8s.node.name=$(K8S_NODE_NAME),host.name=$(K8S_NODE_NAME)'
          ports:
            - name: health-check
              containerPort: 13133
              hostPort: 13133
            - name: metrics
              containerPort: 8888
              hostPort: 8888
            - name: otlp
              containerPort: 4317
              hostPort: 4317
            - name: otlp-http
              containerPort: 4318
              hostPort: 4318
          volumeMounts:
            - name: otel-agent-config-vol
              mountPath: /conf
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: HostToContainer
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            httpGet:
              port: health-check
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              port: health-check
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: otel-agent-config-vol
          configMap:
            name: otel-agent-config-file
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: hostfs
          hostPath:
            path: /
