---
apiVersion: v1
kind: Service
metadata:
  name: otel-agent-service
  labels:
    app: otel-agent
spec:
  type: ClusterIP
  ports:
    - name: health-check
      port: 13133
      targetPort: health-check
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
    - name: otlp
      port: 4317
      targetPort: otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
  selector:
    app: otel-agent
  internalTrafficPolicy: Local
