---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: network
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sysops@wisemen.digital
    privateKeySecretRef:
      name: letsencrypt-certs
    solvers:
      - http01:
          ingress:
            class: nginx
