---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: kube-system
data:
  config.yaml: |
    alerting:
      slack:
        webhook-url: "${SLACK_WEBHOOK_URL}"
      email:
        from: "${MAIL_FROM}"
        username: "${MAIL_USERNAME}"
        password: "${MAIL_PASSWORD}"
        host: ${MAIL_HOST}"
        port: ${MAIL_PORT}
        to: "${MAIL_TO}"
        client:
          insecure: false
    storage:
      type: postgres
      path: "${POSTGRES_URL}"
    metrics: true
    endpoints:
      - name: "${FRONTEND_ENDPOINT_NAME}"
        url: "${FRONTEND_ENDPOINT_URL}"
        interval: 1m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].message == OK"
          - "[RESPONSE_TIME] < ${FRONTEND_ENDPOINT_RESPONSE_TIME}"
        alerts:
          - type: slack
            description: "STARLINE FRONTEND DOWN"
            send-on-resolved: true
            failure-threshold: 1
          - type: email
            description: "STARLINE BACKEND DOWN"
            send-on-resolved: true
            failure-threshold: 1
      - name: "${BACKEND_ENDPOINT_NAME}"
        url: "${BACKEND_ENDPOINT_URL}"
        interval: 1m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].message == OK"
          - "[RESPONSE_TIME] < ${BACKEND_ENDPOINT_RESPONSE_TIME}"
        alerts:
          - type: slack
            description: "STARLINE BACKEND DOWN"
            send-on-resolved: true
            failure-threshold: 1
          - type: email
            description: "STARLINE BACKEND DOWN"
            send-on-resolved: true
            failure-threshold: 1
