---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  labels:
    app: gatus
    service: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: gatus
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: gatus
          image: default-gatus
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: configmap-gatus
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 250m
              memory: 100M
            requests:
              cpu: 50m
              memory: 30M
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /config
              name: gatus-config
      volumes:
        - name: gatus-config
          configMap:
            name: gatus-config
