---
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint YAML & Dockerfile
    uses: wisemen-digital/devops-github-actions/.github/workflows/lint-yaml-and-docker.yml@main
    with:
      enable-docker-linting: false
