---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-doc-processor
  labels:
    app: doc-processor
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: node-doc-processor
          image: default-doc-processor
          imagePullPolicy: Always
          command: ['npm', 'start']
          envFrom:
            - configMapRef:
                name: configmap-api
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 400m
          startupProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
