---
apiVersion: v1
kind: Service
metadata:
  name: node-doc-processor-service
  labels:
    app: node-doc-processor
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: node-doc-processor
